// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { VoiceFlags } from "./VoiceFlags";

export type ClientFrame = { "op": "Hello", "d": { token: string, 
/**
 * [`crate::PROTOCOL_VERSION`] of the client; absent (0) from pre-versioning clients.
 */
client_version: number, } } | { "op": "Heartbeat" } | { "op": "Typing", "d": { channel_id: ChannelId, } } | { "op": "VoiceState", "d": { flags: VoiceFlags, } };
