// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";

export type ClientFrame = { "op": "Hello", "d": { token: string, } } | { "op": "Heartbeat" } | { "op": "Typing", "d": { channel_id: ChannelId, } };
