// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";

/**
 * One other user → a 1:1 `dm` (reused if it exists); 2..=9 others → a new `group`.
 */
export type CreateDmRequest = { user_ids: Array<UserId>, };
