// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { UserId } from "./UserId";

export type DmMembers = { channel_id: ChannelId, user_ids: Array<UserId>, };
