// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { ChannelId } from "./ChannelId";
import type { Member } from "./Member";
import type { Message } from "./Message";
import type { MessageId } from "./MessageId";
import type { Mute } from "./Mute";
import type { Server } from "./Server";
import type { ServerId } from "./ServerId";
import type { User } from "./User";
import type { UserId } from "./UserId";
import type { VoiceFlags } from "./VoiceFlags";

export type Event = { "t": "MessageCreated", "d": { message: Message, nonce: string | null, } } | { "t": "MessageUpdated", "d": { message: Message, } } | { "t": "MessageDeleted", "d": { channel_id: ChannelId, message_id: MessageId, 
/**
 * Who wrote it and whom it mentioned, so clients can take it back out of their
 * unread and mention counts.
 */
author_id: UserId | null, mentions: Array<UserId>, } } | { "t": "ChannelCreated", "d": { channel: Channel, } } | { "t": "ServerCreated", "d": { server: Server, } } | { "t": "MemberJoined", "d": { server_id: ServerId, member: Member, } } | { "t": "Typing", "d": { channel_id: ChannelId, user_id: UserId, } } | { "t": "VoiceJoined", "d": { channel_id: ChannelId, user_id: UserId, 
/**
 * The joiner's current mute/deafen (they may have declared it before the join landed).
 */
flags: VoiceFlags, } } | { "t": "VoiceLeft", "d": { channel_id: ChannelId, user_id: UserId, } } | { "t": "VoiceStateChanged", "d": { channel_id: ChannelId, user_id: UserId, flags: VoiceFlags, } } | { "t": "UserCreated", "d": { user: User, } } | { "t": "PresenceChanged", "d": { user_id: UserId, online: boolean, last_seen_at: string | null, } } | { "t": "GroupMembersChanged", "d": { channel_id: ChannelId, user_ids: Array<UserId>, } } | { "t": "ChannelUpdated", "d": { channel: Channel, } } | { "t": "ChannelRemoved", "d": { channel_id: ChannelId, user_id: UserId, } } | { "t": "ReadStateUpdated", "d": { user_id: UserId, channel_id: ChannelId, last_read_message_id: MessageId | null, } } | { "t": "MutesChanged", "d": { user_id: UserId, mutes: Array<Mute>, } } | { "t": "ConversationVisibility", "d": { user_id: UserId, channel_id: ChannelId, hidden: boolean, } };
