// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { ChannelId } from "./ChannelId";
import type { Member } from "./Member";
import type { Message } from "./Message";
import type { MessageId } from "./MessageId";
import type { Server } from "./Server";
import type { ServerId } from "./ServerId";
import type { UserId } from "./UserId";
import type { VoiceFlags } from "./VoiceFlags";

export type Event = { "t": "MessageCreated", "d": { message: Message, nonce: string | null, } } | { "t": "MessageUpdated", "d": { message: Message, } } | { "t": "MessageDeleted", "d": { channel_id: ChannelId, message_id: MessageId, } } | { "t": "ChannelCreated", "d": { channel: Channel, } } | { "t": "ServerCreated", "d": { server: Server, } } | { "t": "MemberJoined", "d": { server_id: ServerId, member: Member, } } | { "t": "Typing", "d": { channel_id: ChannelId, user_id: UserId, } } | { "t": "VoiceJoined", "d": { channel_id: ChannelId, user_id: UserId, 
/**
 * The joiner's current mute/deafen (they may have declared it before the join landed).
 */
flags: VoiceFlags, } } | { "t": "VoiceLeft", "d": { channel_id: ChannelId, user_id: UserId, } } | { "t": "VoiceStateChanged", "d": { channel_id: ChannelId, user_id: UserId, flags: VoiceFlags, } };
