// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { MessageId } from "./MessageId";
import type { MessageKind } from "./MessageKind";
import type { UserId } from "./UserId";

export type Message = { id: MessageId, channel_id: ChannelId, author_id: UserId | null, kind: MessageKind, content: string, reply_to_id: MessageId | null, created_at: string, edited_at: string | null, deleted: boolean, };
