// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { ChannelId } from "./ChannelId";
import type { DmMembers } from "./DmMembers";
import type { Message } from "./Message";
import type { Mute } from "./Mute";
import type { Person } from "./Person";
import type { ReadState } from "./ReadState";
import type { Server } from "./Server";
import type { ServerMembers } from "./ServerMembers";
import type { User } from "./User";
import type { VoiceRoom } from "./VoiceRoom";

export type Ready = { me: User, servers: Array<Server>, channels: Array<Channel>, members: Array<ServerMembers>, dm_members: Array<DmMembers>, 
/**
 * Who is in which voice room right now (only rooms you may see).
 */
voice: Array<VoiceRoom>, 
/**
 * Everyone with an account, with presence.
 */
people: Array<Person>, 
/**
 * Your private read points with unread/mention counts.
 */
read_states: Array<ReadState>, mutes: Array<Mute>, 
/**
 * Conversations you closed (hidden from your list until a new message).
 */
hidden: Array<ChannelId>, 
/**
 * Latest message of each of your DMs/groups (list previews + sorting).
 */
latest: Array<Message>, };
