// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { DmMembers } from "./DmMembers";
import type { Server } from "./Server";
import type { ServerMembers } from "./ServerMembers";
import type { User } from "./User";

export type Ready = { me: User, servers: Array<Server>, channels: Array<Channel>, members: Array<ServerMembers>, dm_members: Array<DmMembers>, };
