// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { MessageId } from "./MessageId";

export type ReadState = { channel_id: ChannelId, last_read_message_id: MessageId | null, unread: number, mentions: number, };
