// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `None` or blank → back to the default name (the members' names).
 */
export type RenameChannelRequest = { name: string | null, };
