// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerId } from "./ServerId";

export type Server = { id: ServerId, name: string, icon_hash: string | null, };
