// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { Ready } from "./Ready";

export type ServerFrame = { "op": "Ready", "d": Ready } | { "op": "HeartbeatAck" } | { "op": "Event", "d": Event };
