// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MuteTarget } from "./MuteTarget";

export type SetMuteRequest = { target_kind: MuteTarget, target_id: string, until: string | null, };
