// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { VoiceMember } from "./VoiceMember";

export type VoiceRoom = { channel_id: ChannelId, members: Array<VoiceMember>, };
