// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";
import type { VoiceFlags } from "./VoiceFlags";

export type VoiceMember = { user_id: UserId, flags: VoiceFlags, };
